-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2022-01-07 09:54:29 COT
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Cusip 
    (
     CusipId BIGINT NOT NULL IDENTITY(1,1), 
     Code VARCHAR (200) NOT NULL , 
     LotNumber INTEGER NOT NULL , 
     EntityProductId BIGINT NOT NULL 
    )
GO

ALTER TABLE Cusip ADD CONSTRAINT Cusip_PK PRIMARY KEY CLUSTERED (CusipId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

--sdfsdfsd
CREATE TABLE Entity 
    (
     EntityId INTEGER NOT NULL IDENTITY(1,1), 
     EntityName VARCHAR (200) NOT NULL , 
     LineOfBussinessCode VARCHAR (200) NOT NULL , 
     AdhocFlag VARCHAR (1) NOT NULL , 
     EntityType VARCHAR (200) NOT NULL , 
     RelationshipManager VARCHAR (200) NOT NULL , 
     ContactPhone VARCHAR (200) NOT NULL , 
     RegionLocale VARCHAR (200) NOT NULL , 
     Language VARCHAR (200) NOT NULL , 
     ShowConsolidatedHoldingsPage VARCHAR (200) NOT NULL 
    )
GO

ALTER TABLE Entity ADD CONSTRAINT CompanyEntity_PK PRIMARY KEY CLUSTERED (EntityId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE EntityProduct 
    (
     EntityProductId BIGINT NOT NULL IDENTITY(1,1), 
     ProductId INTEGER NOT NULL , 
     EntityId INTEGER NOT NULL , 
     PeriodId INTEGER NOT NULL , 
     LineofBusinessCode VARCHAR (200) NOT NULL , 
     AdhocFlag VARCHAR (1) NOT NULL , 
     SortOrder INTEGER NOT NULL 
    )
GO

ALTER TABLE EntityProduct ADD CONSTRAINT EntityProduct_PK PRIMARY KEY CLUSTERED (EntityProductId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE EntityProductReportFile 
    (
     EntityProductFileId INTEGER NOT NULL IDENTITY(1,1), 
     EntityProductId BIGINT NOT NULL , 
     ReportFileId UNIQUEIDENTIFIER NOT NULL , 
     StartDateTime DATETIME NOT NULL , 
     EndDateTime DATETIME NOT NULL 
    )
GO

ALTER TABLE EntityProductReportFile ADD CONSTRAINT EntityProductReportFile_PK PRIMARY KEY CLUSTERED (EntityProductFileId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE EntityProductValue 
    (
     EntityProductValueId BIGINT NOT NULL IDENTITY(1,1), 
     EntityProductId BIGINT NOT NULL , 
     FieldId UNIQUEIDENTIFIER NOT NULL , 
     Value VARCHAR (200) NOT NULL , 
     CusipId BIGINT NOT NULL 
    )
GO

ALTER TABLE EntityProductValue ADD CONSTRAINT EntityProductValue_PK PRIMARY KEY CLUSTERED (EntityProductValueId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Field 
    (
     FieldId UNIQUEIDENTIFIER NOT NULL , 
     FieldNameInDB VARCHAR (200) NOT NULL , 
     Description VARCHAR (200) NOT NULL , 
     FieldNameInExcel VARCHAR (200) NOT NULL , 
     CreatedOn DATETIME NOT NULL DEFAULT GETDATE(), 
     LastUpdate DATETIME , 
     FieldFormat VARCHAR (200) NOT NULL , 
     IsActive BIT NOT NULL , 
     FieldType VARCHAR (200) NOT NULL , 
     DefaultValue VARCHAR (200) NOT NULL , 
     Granularity VARCHAR (200) NOT NULL 
    )
GO

ALTER TABLE Field ADD CONSTRAINT Field_PK PRIMARY KEY CLUSTERED (FieldId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Period 
    (
     PeriodId INTEGER NOT NULL IDENTITY(1,1), 
     PeriodDate DATE NOT NULL , 
     Description VARCHAR (200) NOT NULL , 
     CreatedOn DATETIME NOT NULL DEFAULT GETDATE(), 
     LastUdptate DATETIME 
    )
GO

ALTER TABLE Period ADD CONSTRAINT Period_PK PRIMARY KEY CLUSTERED (PeriodId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Product 
    (
     ProductId INTEGER NOT NULL IDENTITY(1,1), 
     ProductName VARCHAR (200) NOT NULL , 
     LineofBusinessCode VARCHAR (200) NOT NULL , 
     AdhocFlag VARCHAR (1) NOT NULL 
    )
GO

ALTER TABLE Product ADD CONSTRAINT Product_PK PRIMARY KEY CLUSTERED (ProductId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ReportFile 
    (
     ReportFileId UNIQUEIDENTIFIER NOT NULL IDENTITY(1,1), 
     ReportFileName VARCHAR (200) NOT NULL , 
     Desciption VARCHAR (200) NOT NULL , 
     Path VARCHAR (400) NOT NULL , 
     SortOrder INTEGER NOT NULL , 
     IsActive BIT NOT NULL , 
     CreatedOn DATETIME NOT NULL DEFAULT GETDATE(), 
     LastUpdate DATETIME , 
     ReportType VARCHAR (200) NOT NULL 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'Destination Path' , 'USER' , 'dbo' , 'TABLE' , 'ReportFile' , 'COLUMN' , 'Path' 
GO

ALTER TABLE ReportFile ADD CONSTRAINT Files_PK PRIMARY KEY CLUSTERED (ReportFileId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ReportFileField 
    (
     FileFieldId INTEGER NOT NULL IDENTITY(1,1), 
     ReportFileId UNIQUEIDENTIFIER NOT NULL , 
     FieldId UNIQUEIDENTIFIER NOT NULL , 
     FieldType VARCHAR (200) NOT NULL , 
     FieldFormat VARCHAR (200) NOT NULL , 
     DefaultValue VARCHAR (200) NOT NULL , 
     SortOrderColumn INTEGER NOT NULL , 
     SortOrderRow INTEGER NOT NULL 
    )
GO

ALTER TABLE ReportFileField ADD CONSTRAINT SheetField_PK PRIMARY KEY CLUSTERED (FileFieldId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Cusip 
    ADD CONSTRAINT Cusip_EntityProduct_FK FOREIGN KEY 
    ( 
     EntityProductId
    ) 
    REFERENCES EntityProduct 
    ( 
     EntityProductId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EntityProduct 
    ADD CONSTRAINT EntityProduct_Entity_FK FOREIGN KEY 
    ( 
     EntityId
    ) 
    REFERENCES Entity 
    ( 
     EntityId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EntityProduct 
    ADD CONSTRAINT EntityProduct_Period_FK FOREIGN KEY 
    ( 
     PeriodId
    ) 
    REFERENCES Period 
    ( 
     PeriodId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EntityProduct 
    ADD CONSTRAINT EntityProduct_Product_FK FOREIGN KEY 
    ( 
     ProductId
    ) 
    REFERENCES Product 
    ( 
     ProductId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EntityProductReportFile 
    ADD CONSTRAINT EntityProductFile_EntityProduct_FK FOREIGN KEY 
    ( 
     EntityProductId
    ) 
    REFERENCES EntityProduct 
    ( 
     EntityProductId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EntityProductReportFile 
    ADD CONSTRAINT EntityProductFile_ReportFile_FK FOREIGN KEY 
    ( 
     ReportFileId
    ) 
    REFERENCES ReportFile 
    ( 
     ReportFileId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EntityProductValue 
    ADD CONSTRAINT "EntityProductPort/Cusipv1_Cusip_FK" FOREIGN KEY 
    ( 
     EntityProductId
    ) 
    REFERENCES EntityProduct 
    ( 
     EntityProductId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EntityProductValue 
    ADD CONSTRAINT "EntityProductPort/Cusipv1_Field_FK" FOREIGN KEY 
    ( 
     FieldId
    ) 
    REFERENCES Field 
    ( 
     FieldId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE EntityProductValue 
    ADD CONSTRAINT EntityProductValue_Cusip_FK FOREIGN KEY 
    ( 
     CusipId
    ) 
    REFERENCES Cusip 
    ( 
     CusipId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ReportFileField 
    ADD CONSTRAINT FlieField_File_FK FOREIGN KEY 
    ( 
     ReportFileId
    ) 
    REFERENCES ReportFile 
    ( 
     ReportFileId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ReportFileField 
    ADD CONSTRAINT SheetField_Field_FK FOREIGN KEY 
    ( 
     FieldId
    ) 
    REFERENCES Field 
    ( 
     FieldId 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
