-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2022-01-07 09:54:29 COT
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Parameters.Cusip 
    (
     Cusip_Id BIGINT NOT NULL IDENTITY(1,1), 
     Cusip_Code VARCHAR (200) NOT NULL , 
     Cusip_LotNumber INTEGER NOT NULL , 
     Cusip_EntityProductId BIGINT NOT NULL 
    )
GO

ALTER TABLE Parameters.Cusip ADD CONSTRAINT Cusip_PK PRIMARY KEY CLUSTERED (Cusip_Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Parameters.Entity 
    (
     Entity_Id INTEGER NOT NULL IDENTITY(1,1), 
     Entity_Name VARCHAR (200) NOT NULL , 
     Entity_LineOfBussinessCode VARCHAR (200) NOT NULL , 
     Entity_AdhocFlag VARCHAR (1) NOT NULL , 
     Entity_Type VARCHAR (200) NOT NULL , 
     Entity_RelationshipManager VARCHAR (200) NOT NULL , 
     Entity_ContactPhone VARCHAR (200) NOT NULL , 
     Entity_RegionLocale VARCHAR (200) NOT NULL , 
     Entity_Language VARCHAR (200) NOT NULL ,
     Entity_ShowConsolidatedHoldingsPage VARCHAR (200) NOT NULL 
    )
GO

ALTER TABLE Parameters.Entity ADD CONSTRAINT Entity_PK PRIMARY KEY CLUSTERED (Entity_Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Parameters.EntityProduct 
    (
     EntityProduct_Id BIGINT NOT NULL IDENTITY(1,1), 
     EntityProduct_ProductId INTEGER NOT NULL , 
     EntityProduct_EntityId INTEGER NOT NULL , 
     EntityProduct_PeriodId INTEGER NOT NULL , 
     EntityProduct_LineofBusinessCode VARCHAR (200) NOT NULL , 
     EntityProduct_AdhocFlag VARCHAR (1) NOT NULL , 
     EntityProduct_SortOrder INTEGER NOT NULL 
    )
GO

ALTER TABLE Parameters.EntityProduct ADD CONSTRAINT EntityProduct_PK PRIMARY KEY CLUSTERED (EntityProduct_Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Parameters.EntityProductReportFile 
    (
     EPRF_EntityProductFileId INTEGER NOT NULL IDENTITY(1,1), 
     EPRF_EntityProductId BIGINT NOT NULL , 
     EPRF_ReportFileId INTEGER NOT NULL , 
     EPRF_StartDateTime DATETIME NOT NULL , 
     EPRF_EndDateTime DATETIME NOT NULL 
    )
GO

ALTER TABLE Parameters.EntityProductReportFile ADD CONSTRAINT EntityProductReportFile_PK PRIMARY KEY CLUSTERED (EPRF_EntityProductFileId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Parameters.EntityProductValue 
    (
     EPV_Id BIGINT NOT NULL IDENTITY(1,1), 
     EPV_EntityProductId BIGINT NOT NULL , 
     EPV_FieldId INTEGER NOT NULL , 
     EPV_Value VARCHAR (200) NOT NULL , 
     EPV_CusipId BIGINT NOT NULL 
    )
GO

ALTER TABLE Parameters.EntityProductValue ADD CONSTRAINT EntityProductValue_PK PRIMARY KEY CLUSTERED (EPV_Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Parameters.Field 
    (
     Field_Id INTEGER NOT NULL , 
     Field_NameInDB VARCHAR (200) NOT NULL , 
     Field_Description VARCHAR (200) NOT NULL , 
     Field_NameInExcel VARCHAR (200) NOT NULL , 
     Field_CreatedOn DATETIME NOT NULL DEFAULT GETDATE(), 
     Field_LastUpdate DATETIME , 
     Field_Format VARCHAR (200) NOT NULL , 
     Field_IsActive BIT NOT NULL , 
     Field_Type VARCHAR (200) NOT NULL , 
     Field_DefaultValue VARCHAR (200) NOT NULL , 
     Field_Granularity VARCHAR (200) NOT NULL 
    )
GO

ALTER TABLE Parameters.Field ADD CONSTRAINT Field_PK PRIMARY KEY CLUSTERED (Field_Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Parameters.Period 
    (
     Period_Id INTEGER NOT NULL IDENTITY(1,1), 
     Period_PeriodDate DATE NOT NULL , 
     Period_Description VARCHAR (200) NOT NULL , 
     Period_CreatedOn DATETIME NOT NULL DEFAULT GETDATE(), 
     Period_LastUdptate DATETIME 
    )
GO

ALTER TABLE Parameters.Period ADD CONSTRAINT Period_PK PRIMARY KEY CLUSTERED (Period_Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Parameters.Product 
    (
     Product_Id INTEGER NOT NULL IDENTITY(1,1), 
     Product_ProductName VARCHAR (200) NOT NULL , 
     Product_LineofBusinessCode VARCHAR (200) NOT NULL , 
     Product_AdhocFlag VARCHAR (1) NOT NULL 
    )
GO

ALTER TABLE Parameters.Product ADD CONSTRAINT Product_PK PRIMARY KEY CLUSTERED (Product_Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Parameters.ReportFile 
    (
     ReportFile_Id INTEGER NOT NULL IDENTITY(1,1), 
     ReportFile_Name VARCHAR (200) NOT NULL , 
     ReportFile_Description VARCHAR (200) NOT NULL , 
     ReportFile_Path VARCHAR (400) NOT NULL , 
     ReportFile_SortOrder INTEGER NOT NULL , 
     ReportFile_IsActive BIT NOT NULL , 
     ReportFile_CreatedOn DATETIME NOT NULL DEFAULT GETDATE(), 
     ReportFile_LastUpdate DATETIME , 
     ReportFile_ReportType VARCHAR (200) NOT NULL 
    )
GO 


ALTER TABLE Parameters.ReportFile ADD CONSTRAINT ReportFile_PK PRIMARY KEY CLUSTERED (ReportFile_Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Parameters.ReportFileField 
    (
     RFF_Id INTEGER NOT NULL IDENTITY(1,1), 
     RFF_ReportFileId INTEGER NOT NULL , 
     RFF_FieldId INTEGER NOT NULL , 
     RFF_FieldType VARCHAR (200) NOT NULL , 
     RFF_FieldFormat VARCHAR (200) NOT NULL , 
     RFF_DefaultValue VARCHAR (200) NOT NULL , 
     RFF_SortOrderColumn INTEGER NOT NULL , 
     RFF_SortOrderRow INTEGER NOT NULL 
    )
GO

ALTER TABLE Parameters.ReportFileField ADD CONSTRAINT ReportFileField_PK PRIMARY KEY CLUSTERED (RFF_Id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Parameters.Cusip 
    ADD CONSTRAINT Cusip_EntityProduct_FK FOREIGN KEY 
    ( 
     Cusip_EntityProductId
    ) 
    REFERENCES Parameters.EntityProduct 
    ( 
     EntityProduct_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Parameters.EntityProduct 
    ADD CONSTRAINT EntityProduct_Entity_FK FOREIGN KEY 
    ( 
     EntityProduct_EntityId
    ) 
    REFERENCES Parameters.Entity 
    ( 
     Entity_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Parameters.EntityProduct 
    ADD CONSTRAINT EntityProduct_Period_FK FOREIGN KEY 
    ( 
     EntityProduct_PeriodId
    ) 
    REFERENCES Parameters.Period 
    ( 
     Period_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Parameters.EntityProduct 
    ADD CONSTRAINT EntityProduct_Product_FK FOREIGN KEY 
    ( 
     EntityProduct_ProductId
    ) 
    REFERENCES Parameters.Product 
    ( 
     Product_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Parameters.EntityProductReportFile 
    ADD CONSTRAINT EntityProductFile_EntityProduct_FK FOREIGN KEY 
    ( 
     EPRF_EntityProductId
    ) 
    REFERENCES Parameters.EntityProduct 
    ( 
     EntityProduct_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Parameters.EntityProductReportFile 
    ADD CONSTRAINT EntityProductFile_ReportFile_FK FOREIGN KEY 
    ( 
     EPRF_ReportFileId
    ) 
    REFERENCES Parameters.ReportFile 
    ( 
     ReportFile_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Parameters.EntityProductValue 
    ADD CONSTRAINT "EntityProductPort/Cusipv1_Cusip_FK" FOREIGN KEY 
    ( 
     EPV_EntityProductId
    ) 
    REFERENCES Parameters.EntityProduct 
    ( 
     EntityProduct_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Parameters.EntityProductValue 
    ADD CONSTRAINT "EntityProductPort/Cusipv1_Field_FK" FOREIGN KEY 
    ( 
     EPV_FieldId
    ) 
    REFERENCES Parameters.Field 
    ( 
     Field_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Parameters.EntityProductValue 
    ADD CONSTRAINT EntityProductValue_Cusip_FK FOREIGN KEY 
    ( 
     EPV_CusipId
    ) 
    REFERENCES Parameters.Cusip 
    ( 
     Cusip_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Parameters.ReportFileField 
    ADD CONSTRAINT FlieField_File_FK FOREIGN KEY 
    ( 
     RFF_ReportFileId
    ) 
    REFERENCES Parameters.ReportFile 
    ( 
     ReportFile_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Parameters.ReportFileField 
    ADD CONSTRAINT SheetField_Field_FK FOREIGN KEY 
    ( 
     RFF_FieldId
    ) 
    REFERENCES Parameters.Field 
    ( 
     Field_Id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
