
-- Add the parameters for the stored procedure here
DECLARE @ReportDate DATETIME
DECLARE @PortfolioName VARCHAR(80)
DECLARE @CellGroup VARCHAR(80)

SET @ReportDate = '20201102'
SET @PortfolioName = 'MACON-A'
SET @CellGroup ='BC-IND2'

SELECT CellGroup, CellLabel, CellName, CellLabelOrder, Cusip, SUM(PARAMOUNT) AS ParAmount, MAX(ISSUER) AS Issuer, MAX(COUPON) AS Coupon,
  MAX(MATURITY) AS Maturity, MAX(CASE WHEN WORKOUTCODE IS NULL THEN NULL ELSE WORKOUTDATEBOOK END) AS WorkOutDateBook, MAX(WorkoutCode) AS WorkoutCode, 
  MAX(CASE WHEN (WORKOUTCODE IS NULL) THEN NULL ELSE WORKOUTPRICE END) AS WorkoutPrice,
  MAX(MARKETPRICE) AS Price, SUM(MARKETVALUE) AS MarketValue, MAX(CASE WHEN MOODY IS NULL THEN 'NR' ELSE MOODY END) AS RatingMoodys, 
  MAX(CASE WHEN SP IS NULL THEN 'NR' ELSE SP END) AS RatingSP, MAX(YTW) AS YTW,
  MAX(MDURATION) AS MDuration, SUM(MARKETWEIGHT) AS MarketWeight, MAX(COLLATERALTYPE) AS CollateralType, MAX(RateAvg) AS RateAvg,
  avg(TsySpread) AS TsySpread
FROM (
	SELECT CASE WHEN X.CUSIP = 'CASH' THEN 'CASH' ELSE C.CELLGROUP END AS CELLGROUP, 
		   CASE WHEN X.CUSIP = 'CASH' THEN 'CASH' ELSE C.CELLLABEL END AS CELLLABEL,  
		   CASE WHEN X.CUSIP = 'CASH' THEN 'CASH' ELSE C.CELLNAME END AS CELLNAME, 
		   CASE WHEN X.CUSIP = 'CASH' THEN -1 ELSE C.CELLNAMEORDER END AS CELLLABELORDER,
		   X.CUSIP, X.PARAMOUNT, X.ISSUER, X.COUPON, 
		   CASE WHEN X.CUSIP = 'CASH' THEN NULL ELSE X.MATURITY END AS MATURITY, 
		   X.WORKOUTDATEBOOK, X.WORKOUTCODE,
		   X.WORKOUTPRICE, X.MARKETPRICE, X.MARKETVALUE, M.NAME AS MOODY, S.NAME AS SP, X.YTW, X.MDURATION, 
		   X.MARKETWEIGHT, CASE WHEN X.BCIND2 IS NULL THEN 0 ELSE X.BCIND2 END AS BCIND2,
		   X.COLLATERALTYPE,
		   (SELECT C1.CELLNAME FROM CELLDEF C1 WHERE C1.CELLGROUP = 'RLRAVG' AND C1.CELLNAME NOT IN ('CASH', 'TOTAL') AND C1.CELLGROUPDATE = (SELECT MAX(CD2.CELLGROUPDATE) FROM CELLDEF CD2 WHERE CD2.CELLGROUP = 'RLRAVG')
		     AND C1.CELLEND > ISNULL(X.RATE, ISNULL(ROUND((X.MOODY2 + X.SP2 + X.FITCHCODE)/X.QRATE, 0), 0)) 
			 AND C1.CELLBEGIN <= ISNULL(X.RATE, ISNULL(ROUND((X.MOODY2 + X.SP2 + X.FITCHCODE)/X.QRATE, 0), 0))) AS RateAvg,
		   Development.dbo.GetTsySpread(X.YTW, X.Term, X.IssueDataDate) AS TsySpread
	FROM 
		(SELECT 
		  I.CUSIP, I.LOTNUMBER, I.PARAMOUNT, I.ISSUER,
		  CASE WHEN I.CUSIP = 'CASH' THEN NULL ELSE I.COUPON END AS COUPON, 
		  CASE WHEN I.MATURITY IS NOT NULL THEN I.MATURITY ELSE M.MATURITY END AS MATURITY, 
		  I.WORKOUTDATEBOOK, 
		  case when I.Class='rlpa' or I.Class='rlpg' or I.Class='rlcm' or I.Class='SFPA' or I.Class='SFPL' then 'A' 
				when I.Callable > 0 then 'C'
				when I.Sinkable > 0 then 'S'
				when I.Putable > 0 then ' P'
				when I.CUSIP = 'CASH' then ''
				else null end as WorkoutCode, 
		  CASE WHEN I.CUSIP = 'CASH' THEN NULL ELSE I.WORKOUTPRICE END AS WORKOUTPRICE, 
		  PRICE AS MARKETPRICE, I.MARKETVALUE, 
		  (SELECT TOP 1 R1.CODE FROM RATEHIST R1 WHERE R1.CUSIP = I.CUSIP AND R1.DATE <= I.ISSUEDATADATE AND R1.SOURCE = 'M' ORDER BY R1.DATE DESC) AS MOODY,
		  CASE WHEN I.MoodysCode IS NULL OR I.MoodysCode < 0 THEN 0 ELSE I.MoodysCode END as Moody2,
		  (SELECT TOP 1 R1.CODE FROM RATEHIST R1 WHERE R1.CUSIP = I.CUSIP AND R1.DATE <= I.ISSUEDATADATE AND R1.SOURCE = 'S' ORDER BY R1.DATE DESC) AS SP,
		  CASE WHEN I.StandardPoorsCode IS NULL OR I.StandardPoorsCode < 0 THEN 0 ELSE I.StandardPoorsCode END AS SP2,
		  CASE WHEN I.FitchCode IS NULL OR I.FitchCode < 0 THEN 0 ELSE I.FitchCode END AS FitchCode,
		  (CASE WHEN (I.MoodysCode <= 0) OR (I.MoodysCode IS NULL) THEN 0 ELSE 1 END + 
		  CASE WHEN (I.StandardPoorsCode <= 0) OR (I.StandardPoorsCode IS NULL) THEN 0 ELSE 1 END + 
		  CASE WHEN (I.FitchCode <= 0) OR (I.FitchCode IS NULL) THEN 0 ELSE 1 END + 0.001) AS QRATE,
		  I.YTW, I.MDURATION, I.MARKETWEIGHT, I.DURATION, I.TERM, ISNULL(I.MOODYSCODE, 0) AS MOODYSCODE, I.INDUSTRYCODE, I.ISSUEDATADATE,
		  (SELECT TOP 1 ISNULL(IG.IndustryGroupCode,-1)
			FROM INDUSTRYGROUPS IG 
			WHERE IG.IndustryGroupCode = (SELECT CD_Temp.CELLEND FROM CELLDEF CD_Temp WHERE CD_Temp.CELLGROUP = 'BC-IND2' AND CD_Temp.CELLBEGIN = IG.IndustryGroupCode)
			  AND IG.INDUSTRYCODE = SIC.INDUSTRYCODE) AS BCIND2,
		  (SELECT AVG(CAST(H.CODE AS FLOAT)) FROM RATEHIST H WHERE H.CUSIP = I.CUSIP AND H.DATE = (SELECT MAX(H1.DATE) FROM RATEHIST H1 WHERE H1.CUSIP = H.CUSIP AND H1.SOURCE = H.SOURCE AND H1.DATE <= I.ISSUEDATADATE AND H.CODE > 0 /*AND H1.DATE >= SI.IssueDate*/) AND H.CODE > 0) AS RATE,
		  I.COLLATERALTYPE
		FROM ISSUEDATA I
			LEFT JOIN MATURITYDATES M ON M.CUSIP = I.CUSIP AND M.DATE = (SELECT MAX(M1.DATE) FROM MATURITYDATES M1 WHERE M1.CUSIP = M.CUSIP)
			LEFT JOIN SECINDUSTRYCODE SIC ON SIC.CUSIP = I.CUSIP AND SIC.SOURCE = 'BCAP'
			LEFT JOIN SECINFO SI ON SI.Cusip = I.Cusip
		WHERE I.PORTFOLIONAME = @PortfolioName AND I.ISSUEDATADATE = @ReportDate
		AND I.CUSIP != 'CASH'
		) X
	LEFT JOIN RATEMAP M ON M.SOURCE = 'M' AND M.CODE = ISNULL(X.MOODY, ISNULL(X.MOODY2, 0)) AND M.CODERANK = 1 
	LEFT JOIN RATEMAP S ON S.SOURCE = 'S' AND S.CODE = ISNULL(X.SP, ISNULL(X.SP2, 0)) AND S.CODERANK = 1 
	LEFT JOIN [StandardData].[dbo].[CellDefCatalogue] D ON D.CELLGROUP = @CellGroup
	LEFT JOIN CELLDEF C ON C.CELLGROUP = D.CELLGROUP
		AND C.CELLEND > 
		CASE WHEN D.CELLTYPE = 1 THEN CASE WHEN X.BCIND2 IS NULL THEN -1 ELSE X.BCIND2 - 1 END
		WHEN D.CELLTYPE = 2 THEN CASE WHEN X.MDURATION = 0 THEN 0.01 ELSE X.MDURATION END
		WHEN D.CELLTYPE = 3 THEN X.TERM
		WHEN D.CELLTYPE = 4 THEN CASE WHEN X.DURATION = 0 THEN 0.01 ELSE X.DURATION END
		WHEN D.CELLTYPE = 45 THEN ISNULL(X.RATE, ISNULL(ROUND((X.MOODY2 + X.SP2 + X.FITCHCODE)/X.QRATE, 0), 0))
		ELSE X.TERM END
		AND C.CELLBEGIN <= 
		CASE WHEN D.CELLTYPE = 1 THEN CASE WHEN X.BCIND2 IS NULL THEN -1 ELSE X.BCIND2 END
		WHEN D.CELLTYPE = 2 THEN CASE WHEN X.MDURATION = 0 THEN 0.01 ELSE X.MDURATION END
		WHEN D.CELLTYPE = 3 THEN X.TERM
		WHEN D.CELLTYPE = 4 THEN CASE WHEN X.DURATION = 0 THEN 0.01 ELSE X.DURATION END
		WHEN D.CELLTYPE = 45 THEN ISNULL(X.RATE, ISNULL(ROUND((X.MOODY2 + X.SP2 + X.FITCHCODE)/X.QRATE, 0), 0))
		ELSE X.TERM END
		AND C.CELLNAME NOT IN ('CASH', 'TOTAL')
		AND C.CELLGROUPDATE = (SELECT MAX(CD2.CELLGROUPDATE) FROM CELLDEF CD2 WHERE CD2.CELLGROUP = C.CELLGROUP)
	) AS DATA 
GROUP BY CELLGROUP, CELLLABEL, CELLNAME, CELLLABELORDER, CUSIP

ORDER BY CellLabelOrder, Cusip
